echo backupmd图床数据……
rsync.exe -avPzruh  --port 8730 --password-file=/cygdrive/d/vitepress-theme-teek-online-install-one-privateshell/password.txt  root@你服务器ip::cmi-MdImages/ /cygdrive/D/BaiduSyncdisk/backup/rsync_local/cmi-MdImages-local-20250306
